### ISSUE TITLE
Elm 0.19 support

### ISSUE THREAD

**Issue by AntonLebiodkin** [elm-community/list-split#5]
Will this package have elm 0.19 support?

**Comment by prikhi** [comment]
@AntonLebiodkin This is a pretty simple package, would you be into updating it and submitting a PR?

**Comment by prikhi** [comment]
@AntonLebiodkin I updated this for 0.19 & pushed a new version.

@jonboiser There were no code changes(just `elm-package.json` -> `elm.json`) so I took care of this, hope you don't mind.
